language: julia
os:
  - linux
julia:
  - release
notifications:
  email: false
install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - wget http://ci.arrayfire.org/userContent/Linux/ArrayFire-no-gl-v3.3.2_Linux_x86_64.sh
  - ./ArrayFire-no-gl-v3.3.2_Linux_x86_64.sh
before_script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/$USER/ArrayFire-no-gl-v3.3.2_Linux_x86_64/
script:
  - julia --check-bounds=yes -e 'Pkg.add("ArrayFire"); Pkg.test("ArrayFire")'
